### ISSUE TITLE
onPress not fired for email custom pattern

### ISSUE THREAD

**Issue by FaridSafi** [taskrabbit/react-native-parsed-text#1]
Hello, thank you for this very useful component.

I tried to implement an email parsing using the following option:
        {pattern: /^\S+@\S+$/, style: {textDecorationLine: 'underline'}, onPress: () => { console.log('email pressed'); }},

The text is underlined properly but nothing happens when I press the word.
Do you experiment the same issue?

react-native 0.14.2
npm 2.14.7
nodejs 4.2.2

**Comment by jrichardlai** [comment]
Ok thanks I'll take a look

**Comment by jrichardlai** [comment]
the regexp you are using is a global regexp you should just use `/\S+@\S+/`

**Comment by jrichardlai** [comment]
( also seems that the regexp url im using is too permissive )

**Comment by jrichardlai** [comment]
I just added email as a pattern and the url pattern is updated in 0.0.4

**Comment by jrichardlai** [comment]
Did that work @FaridSafi ?

**Comment by FaridSafi** [comment]
I will test it today, thank you

**Comment by FaridSafi** [comment]
Email type is working well, thx!
I'm about to release a Chat interface component. I will integrate react-native-parsed-text in it

**Comment by FaridSafi** [comment]
https://github.com/FaridSafi/react-native-gifted-messenger

**Comment by jrichardlai** [comment]
Looks good! awesome work!
