### ISSUE TITLE
Pass matches result to renderText

### ISSUE THREAD

**Issue by vitalets** [taskrabbit/react-native-parsed-text#12]
hi!
It would be great to pass pattern matches as second param to `renderText`. That is easy and allows to avoid duoble regex parsing of already matched str.
I mean if I want to replace `aa{text}bb` with bold I just write
```js
pattern: /\{(.+)\}/,
style: fontWeight: 'bold',
renderText: (str, matches) => matches[1]

**Comment by jrichardlai** [comment]
yes that makes sense

**Comment by jrichardlai** [comment]
should be good in 0.0.11 sorry for the late response

**Comment by vitalets** [comment]
thank you!
