### ISSUE TITLE
babel dependencies

### ISSUE THREAD

**Issue by FaridSafi** [taskrabbit/react-native-parsed-text#18]
Hello @jrichardlai,
Do you think it's possible to get rid of all babel dependencies ? Why are they needed ?

**Comment by jrichardlai** [comment]
Hey @FaridSafi! Yeah I can do that, they are probably not needed :)

**Comment by jrichardlai** [comment]
Let me know if v0.0.15 works

**Comment by jrichardlai** [comment]
@FaridSafi is this good for you now?

**Comment by jrichardlai** [comment]
@FaridSafi did you had time to take a look?

**Comment by FaridSafi** [comment]
Sorry for late reply, yes it works great! Thanks @jrichardlai

**Comment by FaridSafi** [comment]
Next step will be to remove of all of them :D 
Or maybe there is a preset for whats needed

**Comment by chirag04** [comment]
`babel-preset-react-native-stage-0` does that cover everything?
