### ISSUE TITLE
Can this work with TextInput?

### ISSUE THREAD

**Issue by sixcycle-personal** [taskrabbit/react-native-parsed-text#20]
Can this be made to work live with a TextInput? My current thought would be to have a `<ParsedText />` component that is controlled by a hidden `<TextInput />` but that doesn't feel right... Any thoughts?

**Comment by kristojorg** [comment]
Any update here? Is there a way to render a parsed text component over top of a text input maybe?

**Comment by jrichardlai** [comment]
Not sure if its possible, I think the tap behavior would be handled by the TextInput, maybe a hidden TextInput can work.

**Comment by kristojorg** [comment]
Update - Just nest a `<ParsedText>` within the `TextInput` and it will work:

```
return (
  <TextInput
    \\ value={this.props.value} (leave out the value prop of text input
  />
    <ParsedText {...this.props} >{this.props.value}</ParsedText>
  </TextInput>
)
```

**Comment by Un3qual** [comment]
Note that @kristojorg's solution only works if your parsed output is the same as the input. For example, if you are replacing `some **bold** text` with 
> some **bold** text

this will not work because as soon as the parser removes the `**`s, the text input updates, triggering the input to be re-parsed (without the `**`).

**Comment by zeflash** [comment]
@Un3qual do you have a solution for this? I have the same problem, trying to include "extra data" & keep it while I'm editing things up.

**Comment by bockc** [comment]
Looking for a way to make this work with a TextInput as well :/

**Comment by fukemy** [comment]
i tried but not working to me, im using giftedChat and it's does not support mention, im stucking and want to gangbang my head with this

**Comment by Raorakshith** [comment]
> Note that @kristojorg's solution only works if your parsed output is the same as the input. For example, if you are replacing "some **bold** text" with "some **bold** text", this will not work because as soon as the parser removes the `**`s, the text input updates, triggering the input to be re-parsed (without the `**`).

Did you find the solution for this
