### ISSUE TITLE
Child Text components do not respect `allowFontScaling={false}`

### ISSUE THREAD

**Issue by ajwhite** [taskrabbit/react-native-parsed-text#29]
Child Text components [do not inherit any properties from their parent](https://github.com/taskrabbit/react-native-parsed-text/blob/v0.0.10/src/ParsedText.js#L56-L63) -- rightfully so, we wouldn't want `onLayout` being passed to all the child Text components, and React Native does a good job of [automatically passing down style and display related rules with text nesting](https://facebook.github.io/react-native/docs/text.html#nested-text).

However, `allowFontScaling` does not make its way down here automatically. 

Example
```js
<Text allowFontScaling={false} style={{fontSize: 14}}>A normal text node</Text>
<ParsedText allowFontScaling={false} style={{fontSize: 14}} parse={rules}>
  Hello world.
  https://www.google.com.
  End of example.
</ParsedText>
```

Which yields
<img src="https://cloud.githubusercontent.com/assets/656630/23714072/fa63bf46-03f5-11e7-941f-f3f2a022127e.png" height="450" />

**Comment by fbartho** [comment]
Fixed by #29
