### ISSUE TITLE
renderText prop not updated using HMR

### ISSUE THREAD

**Issue by ariona** [taskrabbit/react-native-parsed-text#30]
Hi, Thanks for this great module, it's really help me getting my work done. However there is small issue with renderText prop and HMR. I can't see it updated when there is a changes in my code.

I need to manually reload the app to get the result. Is it normal behaviour?

**Comment by fbartho** [comment]
I think this is a bug, if someone wants to find a fix for react-native-parsed-text & hot-module-reloading, I'd be happy to review the PR

**Comment by fbartho** [comment]
I believe this ticket is no longer relevant because React has moved to Fast Refresh

Happy to reopen if needed.

If you find a bug or have a PR, I'm working on a new release in #79
