### ISSUE TITLE
Does not consider Test.com to be a URL

### ISSUE THREAD

**Issue by devbriguy** [taskrabbit/react-native-parsed-text#32]
Hi, great module. I was trying out Test.com or Test.org and these would not be discovered as URL. Any chance this is expected or it's a bug? Thanks in advance.

**Comment by sventech** [comment]
From the example it looks like you need to specify `http://test.com` instead of just `test.com`. You could add another custom URL handler to cover the common TLDs (com,org,net,io,etc.)

**Comment by devbriguy** [comment]
Hi @sventech Yeah that's what I did: 

```javascript
{
  pattern: /[-a-zA-Z0-9:%._\+~#=]{2,256}\.[a-zA-Z]{2,6}\b/, 
  style: linkStyle, 
  onPress: this.onUrlPress
}
```
