### ISSUE TITLE
Not parsing when 2 variables

### ISSUE THREAD

**Issue by RaphArbuz** [taskrabbit/react-native-parsed-text#43]
Strange thing:
`<ParsedText ...>{a} {b}</ParsedText>`
does not get parsed but
`<ParsedText ...>{a + ' ' + b}</ParsedText>`
does.
I don't know if it's a bug or if I'm doing something wrong.

Many thanks!

**Comment by thinklinux** [comment]
The problem probably is that for react `{a} {b}` translates to tree children like so ['a', ' ', 'b'] and `{a + ' ' + b}` is only one child which is just a simple string not an array of strings. I think the code is assuming that you have only one child inside `<ParsedText>`. I'm not sure that that's a bug tho. And you are not doing anything wrong for sure.

**Comment by fbartho** [comment]
This is a limitation of how React works. Depending on your exact code, I'd say you could use the latter pattern that you suggested in your issue description.

If you want, you can make a special component that uses the React.Children APIs to concatenate all the strings for you into a single component.

I'm going to close this ticket as it's over 2 years old, but if you think you still want to discuss it, we can reopen!

If you find a bug or have a PR, I'm working on a new release in #79

**Comment by phatmann** [comment]
This should be documented clearly. Must be a single child! This cost me HOURS of head scratching!
