### ISSUE TITLE
Support IP & IP:PORT hostnames in URL pattern

### ISSUE THREAD

**Issue by webraptor** [taskrabbit/react-native-parsed-text#46]
Currently the URL pattern doesn't match IP and IP:PORT hostnames.
It supports only FQDN because the regex requires the TLD to be present.

**Current regex**
/(https?:\/\/|www\.)[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)/i

**Proposed regex**
/(https?:\/\/|www\.)[-a-zA-Z0-9@:%._\+~#=]{2,256}**(**\.[a-z]{2,6}**)?**\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)/i
if not very clear by bolding, \.[a-z]{2,6} became (\.[a-z]{2,6})?

Ideally the URL pattern should be according to RFC 3986 or the newer version RFC 7595

**Comment by fbartho** [comment]
@webraptor
I worry that this would start matching undesirable things as so many chunks are optional.

If you want to submit a PR we could potentially see what it looks like & add tests.

Alternatively, obviously, you can override the regexp yourself for some components, or you can in the next release directly patch the `PATTERNS` table, if you want to apply this fix globally for yourself.

https://github.com/taskrabbit/react-native-parsed-text/blob/cfd4ee632f04e60aee6e10a806994e6d3dde9cd8/src/ParsedText.js#L7-L11

**Comment by fbartho** [comment]
I'm going to close this ticket as I provided workarounds 2 years ago! (time flies)

If this is still interesting, we can reopen the ticket.

If you find a bug or have a PR, I'm working on a new release in #79
