### ISSUE TITLE
Doesn't work with react-native 0.16.0 due to babel

### ISSUE THREAD

**Issue by dbrugne** [taskrabbit/react-native-parsed-text#5]
```TransformError: /.../node_modules/react-native-parsed-test/lib/libTextExtraction.js: [BABEL] /.../node_modules/react-native-parsed-text/lib/lib/TextExtraction.js: Unknown option: /.../node_modules/react-native-parsed-text/package.json.stage```

I think you should rely on Babel 6 (as RN0.16.0) to translate code but I wasn't able to find a configuration that work. :)

Above this, what's the interest of distributing build code (lib/*) in npm? You module should be used only in RN context and a build process is already done by react-native during packaging.

**Comment by jrichardlai** [comment]
Yeah right, I will remove that, react-native should take care of the compilation.

**Comment by dbrugne** [comment]
Great!

**Comment by jrichardlai** [comment]
the 0.0.7 should be good, let me know!
