### ISSUE TITLE
Replace the phone and email into the chat with *******

### ISSUE THREAD

**Issue by AkAyush** [taskrabbit/react-native-parsed-text#50]
Issue Description

Hi, I am using react-native-gifted-chat and I wanted to know, how to restrict the user to input any phone number or email address in chat ??

In My second scenario, I want to replace my chated phone number or email with ********* so that the end user cant see the shared number or email for the privacy reason.

PLEASE HELP I AM NEW WITH THIS LIBRARY

React version: "16.3.1"
React Native version: 0.55.1
react-native-gifted-chat version: ^0.4.3
Platform(s) (iOS, Android, or both?): both

**Comment by fbartho** [comment]
Hi @AkAyush -- if you're still interested in this type of thing, one way you could do this is with a recognizer:

```js
{
  type:phone,
  style: styles.phone,
  onPress: this.handlePhonePress,
  renderText: hideText
}
```
You then would provide your own renderText function that does something like:
```js
const hideText = text => {
  return (text || '')
    .split('')
    .map(character=> '*')
    .join('');
}
```

You can get as fancy or as simple as you want! Message back if you need further help.
