### ISSUE TITLE
Add Typescript definition

### ISSUE THREAD

**Issue by xcarpentier** [taskrabbit/react-native-parsed-text#57]
Hi,
Thanks for this project.
I'm using TypeScript.
It will be great to add a definition file.
Thanks.

**Comment by plus-** [comment]
https://github.com/taskrabbit/react-native-parsed-text/pull/55

**Comment by fbartho** [comment]
Happy to say that this did merge, and will be in the next deploy.

If you find a bug or have a PR, I'm working on a new release in #79 

I'm going to close this issue for now, but happy to reopen it if we still need to discuss this. At some future date I'd also consider converting this whole library to TypeScript, but that's a future discussion.
