### ISSUE TITLE
How to use variable in Regex?

### ISSUE THREAD

**Issue by Albert0405** [taskrabbit/react-native-parsed-text#60]
This is my code and i wanted to parsed a dynamic string from an array unfortunately it gave an error saying `Type Error: pattern.pattern.exec is not a function`. I believe im doing it wrong becaue i dont know how to use a variable on regex string
```
                  {this.state.data.map(names => (
                    <ParsedText
                      parse={[
                        { pattern: names, style: { color: '#ff0000' } }
                      ]}
                    >
                      some long texts here........
                    </ParsedText>
                  ))}
```

**Comment by hossamnasser938** [comment]
`map` function returns a new array. Are you sure you want to return an array of `ParsedText`?

**Comment by LucDrenth** [comment]
If anybody is still wondering, you can use variables by using `RegExp`
Place the variable in RegExp to only use the variable or surround the content inside the RegExp with \`\` and then use your variable like this `${variable}`
```
myVariable = 'styleThisWord'

...
pattern: new RegExp(myVariable)
...
pattern: new RegExp(` |^${myVariable}`)
...
```
