### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by hugomosh** [taskrabbit/react-native-parsed-text#62]
I see some open issues and last update from nov 2018. I am wondering if the repo is updated or shall we search for alternatives? Or help to maintain it?

**Comment by fbartho** [comment]
@hugomosh @gianpaj @kdbcinco-cs @levgenRagulin -- I'm happy to say this library is still maintained. We just lost track of Github Notifications / Pull Requests

Is this something you're still interested in discussing? I'm going to close this for now, as it's over a year old, but if this is still interesting to discuss, we can reopen the ticket.

If you find a bug or have a PR, I'm working on a new release in #79
