### ISSUE TITLE
Using linkify as parser or another library

### ISSUE THREAD

**Issue by gianpaj** [taskrabbit/react-native-parsed-text#63]
See the demo https://soapbox.github.io/linkifyjs/

and the docs section "Find all links in the given string"

https://soapbox.github.io/linkifyjs/docs/
```js
linkify.find('Any links to github.com here? If not, contact test@example.com');

[
  {
    type: 'url',
    value: 'github.com',
    href: 'http://github.com'
  },
  {
    type: 'email',
    value: 'test@example.com',
    href: 'mailto:test@example.com'
  }
]
```

**Comment by fbartho** [comment]
@gianpaj this is neat, but sort of feels like an *alternative* to this library.

Is this something you're still interested in discussing? I'm going to close this for now, as it's over a year old, but if this is still interesting, we can reopen the ticket.

If you find a bug or have a PR, I'm working on a new release in #79
