### ISSUE TITLE
URl preview

### ISSUE THREAD

**Issue by Chahdro** [taskrabbit/react-native-parsed-text#64]
Possibility to add url preview on parsed text 
![image](https://user-images.githubusercontent.com/11610859/60506442-be7b1480-9cbd-11e9-9aa5-f2d85ad9046c.png)

**Comment by fbartho** [comment]
@Chahdro -- this is a great idea. It's unfortunately much more complex than it sounds, and probably out-of-scope for this library.

That said: if somebody implements the feature discussed in #68, then you'd be able to build this on your side and glue in a `<LinkPreview>` component.

I'm going to close this for now, but if you or others are motivated, we can keep discussing it here, and I'm happy to reopen the ticket.

If you find a bug or have a PR, I'm working on a new release in #79
