### ISSUE TITLE
Text returned from method is not getting parsed

### ISSUE THREAD

**Issue by Kiran0791** [taskrabbit/react-native-parsed-text#65]
Hi,
 
In my case the text is returned from a function.

 <ParsedText 
parse={
                            [
                            {type: 'url', style: {color:"red"}, onPress: this.handleUrlPress},
                            ]
                        }
        >
         {format(answers)} </ParsedText>

in this case the parse is not happening

Help me on this

Thanks

**Comment by passerbyloo** [comment]
how to handle this case.
