### ISSUE TITLE
How to use I18n to make pattern

### ISSUE THREAD

**Issue by passerbyloo** [taskrabbit/react-native-parsed-text#67]
I want to match a constant, which is return from `I18n.t('test')`.

But the pattern don't know how to handle it. I try `pattern: /I18n.t('test')/` but it not work

**Comment by passerbyloo** [comment]
found it

**Comment by saadqbal** [comment]
Hey @passerbyloo how did you solve it ?

**Comment by passerbyloo** [comment]
> Hey @passerbyloo how did you solve it ?

`pattern: new RegExp(I18n.t(''))`
