### ISSUE TITLE
parse the state

### ISSUE THREAD

**Issue by copper123** [taskrabbit/react-native-parsed-text#76]
How can I parse the variable from this.state.xx? the code below give no help

<ParsedText
     style={styles.text}
     parse={
     [
        {pattern: /{this.state.search}/,style: styles.found},
     ]
      }
childrenProps={{allowFontScaling: false}}
>
blahblah
</ParsedText>

**Comment by dhruvdewangupta** [comment]
try

`pattern: /${this.state.search}/`

**Comment by copper123** [comment]
thanks dhruvdewangupta, but it does not work

**Comment by JongGyuChoi** [comment]
i found the solution 
try
pattern : RegExp(variable)

**Comment by fbartho** [comment]
Closing the issue since there's a suggested solution. Please let me know if that doesn't work @copper123 

If you find a bug or have a PR, I'm working on a new release in #79

**Comment by copper123** [comment]
Sorry for the late.
Still does not work
@JongGyuChoi  do you mean  
pattern : RegExp(/{this.state.search}/)
