### ISSUE TITLE
Google maps URL not getting parsed due to comma

### ISSUE THREAD

**Issue by raazatul7** [taskrabbit/react-native-parsed-text#82]
I have this link from google maps - "http://maps.google.com/?q=28.6079884,77.0891879"
I use react-native gifted chat to open the link on clicked but the problem is when I use parsed method the URL I get is - "http://maps.google.com/?q=28.6079884"
Which is wrong.
Let me know what should I do to get the full URL.

**Comment by fbartho** [comment]
Shipped in https://github.com/taskrabbit/react-native-parsed-text/releases/tag/v0.0.22 ! @raazatul7 -- please let me know if you have any issues.
