### ISSUE TITLE
Invariant Violation: StaticRenderer

### ISSUE THREAD

**Issue by georgi-kovachev** [taskrabbit/react-native-parsed-text#9]
I am getting this error

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `StaticRenderer

from

let parse = [
        {type: 'url', style: [styles.link, (rowData.position === 'left' ? styles.linkLeft : styles.linkRight)], onPress: this.handleUrlPress},
        {type: 'phone', style: [styles.link, (rowData.position === 'left' ? styles.linkLeft : styles.linkRight)], onPress: this.handlePhonePress},
        {type: 'email', style: [styles.link, (rowData.position === 'left' ? styles.linkLeft : styles.linkRight)], onPress: this.handleEmailPress}
      ];

      return (
        <ParsedText
          style={[styles.text, (rowData.position === 'left' ? styles.textLeft : styles.textRight)]}
          parse={parse}          
        >
        </ParsedText>
      );

Any idea.

**Comment by jrichardlai** [comment]
which version are you using ? also what is the text passed to ParsedText ? thanks

**Comment by georgi-kovachev** [comment]
I am using react native version 0.16.0
react-native-parsed-text: 0.0.9
https://github.com/taskrabbit/react-native-parsed-text

Thanks

**Comment by georgi-kovachev** [comment]
Sorry I misunderstood text is empty, although I specified some string, it has same error

**Comment by jrichardlai** [comment]
Does it has the same error if you wrap it inside a View?

**Comment by georgi-kovachev** [comment]
Yes I did it like this.
return (
        <View>
          <ParsedText
            style={[styles.text, (rowData.position === 'left' ? styles.textLeft : styles.textRight)]}
            parse={parse}          
          >
          </ParsedText>
        </View>
      );
But same error.

**Comment by georgi-kovachev** [comment]
I even changed like this.
return (
        
        <ParsedText>          
        </ParsedText>
        
      );
But same error.

FYI My class is extending component class.
and other elements are working.

class Chatpage extends Component{
}

**Comment by georgi-kovachev** [comment]
I changed from 'require' to 'import' and it works.
// var ParsedText = require('react-native-parsed-text');
import ParsedText from 'react-native-parsed-text';

But in one of working example of using ParsedText it works with ParsedText.
Maybe that example is using old version?
I am not sure why.
I am closing the issue now.
Thanks

**Comment by fender** [comment]
Thanks @georgi-kovachev 

Why do we have to use `import..` ? For all other modules I am able to use `require(..)`.

**Comment by bensinc** [comment]
I'm also having this issue, and am using "import:" import { ParsedText } from 'react-native-parsed-text'

My versions:

react-native-cli: 1.0.0
react-native: 0.33.0

The text doesn't seem to matter. It can be blank, have matching URLs, or no matches, and still fails.

**Comment by jrichardlai** [comment]
try `import ParsedText from 'react-native-parsed-text';`
